
#define TIMER_ADDR                  0x00000000

#define LED_READ_ADDR               0x00010000
#define LED_WRITE_ADDR              0x00010004
#define	LED_DIR_ADDR                0x00010008

#define LED_MEM_ADDR                0x00020000

#define HUB75_STREAMER_CONFIG_ADDR    0x00030000

#define HUB75_STREAMER_CONFIG_ENABLE_FIELD_START                0
#define HUB75_STREAMER_CONFIG_ENABLE_FIELD_LENGTH               1

#define HUB75_STREAMER_CONFIG_START_FIELD_START                 1
#define HUB75_STREAMER_CONFIG_START_FIELD_LENGTH                1

#define HUB75_STREAMER_CONFIG_AUTO_RESTART_FIELD_START          2
#define HUB75_STREAMER_CONFIG_AUTO_RESTART_FIELD_LENGTH         1

#define HUB75_STREAMER_CONFIG_BUFFER_NR_FIELD_START             4
#define HUB75_STREAMER_CONFIG_BUFFER_NR_FIELD_LENGTH            1


#define HUB75_STREAMER_STATUS_ADDR    0x00030004

#define HUB75_STREAMER_STATUS_CUR_PANEL_NR_FIELD_START          0
#define HUB75_STREAMER_STATUS_CUR_PANEL_NR_FIELD_LENGTH         4

#define HUB75_STREAMER_STATUS_CUR_ROW_NR_FIELD_START            8
#define HUB75_STREAMER_STATUS_CUR_ROW_NR_FIELD_LENGTH           5

#define HUB75_STREAMER_STATUS_CUR_BIT_NR_FIELD_START            16
#define HUB75_STREAMER_STATUS_CUR_BIT_NR_FIELD_LENGTH           3

#define HUB75_STREAMER_STATUS_CUR_BUFFER_NR_FIELD_START         31
#define HUB75_STREAMER_STATUS_CUR_BUFFER_NR_FIELD_LENGTH        1
