
rick_32x23-0.rgb: rick_orig.gif
	convert -resize 32x23 rick_orig.gif rick_32x23.gif
	convert rick_32x23.gif rick_32x23.png
	convert rick_32x23-0.png rick_32x23-0.rgb


clean: 
	rm -f rick_32x24.gif *.png *.rgb
